baseURL: "https://el-uhu.github.io/clemenshofer-website-source/"
title: Clemens Hofer
paginate: 7
theme: PaperMod
publishDir: docs

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Clemens Hofers Schriften
    description: ""
    keywords: [Blog, Portfolio, PaperMod]
    author: Clemens Hofer
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "02.01.2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: true
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    # label:
    #     text: "Clemens Hofer"
    #     icon: /apple-touch-icon.png
    #     iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title:  " "
        subtitle: ""
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: " "
        buttons:
            - name: Reisebilder
              url: tags/reisebilder
              imageUrl: img/Dreysine2.png
            - name: Heimatverdichtung
              url: tags/heimatverdichtung
              imageUrl: img/Hand-with-Tanne2.png

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    # socialIcons:
    #     - name: twitter
    #       url: "https://twitter.com/"
    #     - name: stackoverflow
    #       url: "https://stackoverflow.com"
    #     - name: github
    #       url: "https://github.com/"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # editPost:
    #     URL: "https://github.com/<path_to_repo>/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: Über Clemens
          name: Über Clemens
          url: /about
          weight: 10
          weight: 20
        - identifier: Reisebilder
          name: Reisebilder
          url: /tags/reisebilder
          weight: 30
        - identifier: Heimatverdichtung
          name: Heimatverdichtung
          url: /tags/Heimatverdichtung
          weight: 40


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
